# Generated by Django 3.1 on 2020-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('description', models.CharField(max_length=1000)),
                ('duaration', models.IntegerField(default=30)),
            ],
        ),
    ]
